describe('empty spec', () => {
  it('passes', () => {
    cy.visit('https://aprass.studio')
    cy.get('.header__top__right > :nth-child(2) > a').click()
    cy.get('#rname').type("New User")
    cy.get('#rbirth').type("2000-01-01")
    cy.get('#rmale').click()
    cy.get('#rtelp').type("0888888888888")
    cy.get('#remail').type("newuser@gmail.com")
    cy.get('#rusername').type("newuser")
    cy.get('#rpassword').type("password123")
    cy.get('#rpassword_confirmation').type("password123")
    cy.get('#raddress').type("Jalan Mawar no 1")
    cy.get('#rpostal_code').type("65122")
    cy.get('#rcity').type("Malang")
    cy.get('#rprovince').type("Jawa Timur")
    cy.get('#signupbtn').click()
  })
})